name: Swift

on:
  push:
    branches: [ com.master.key ]
  pull_request:
    branches: [ onion.master.key ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
